# Generated by Django 4.2.17 on 2024-12-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='longitude',
        ),
        migrations.AddField(
            model_name='poi',
            name='coordenada_x',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi',
            name='coordenada_y',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
